Remove format date because this error
schema schema.json is invalid
error: unknown format "date" ignored in schema at path "#/properties/yasunori/items/properties/date"